### ISSUE TITLE
move_interface

### ISSUE THREAD

**Issue by dipendras** [UTNuclearRoboticsPublic/contact_control#1]
I am trying to use the package, but I have the issue with the package move_interface. Is it the separate package that is required in order to use contact_control?
Thanks in advance

**Comment by AndyZe** [comment]
So contact_control depends on one of our private packages. Maybe we should make move_interface public?

**Comment by dipendras** [comment]
It would be of great help if you can make the move_interface package public. Otherwise it would be difficult  to use the contact_control package. Moreover, I am currently working with contact_control, so I would be grateful.

**Comment by AndyZe** [comment]
@dipendras There's a public repo here now (for Indigo). https://github.com/UTNuclearRoboticsPublic/move_interface

@Kukanani will add a Kinetic branch soon.

**Comment by dipendras** [comment]
Thank you so much.

**Comment by AndyZe** [comment]
Hey @dipendras, we decided we can't support move_interface in the public domain. There are too many dependencies on the rest of our code to sort out right now. Unfortunately we're going to delete the public repo. So I guess there are 3 options for you:

- Keep the move_interface source code you have now, but realize the repo is going to be deleted. If you didn't clone it yet, I can email you a copy.
- Go through the code of contact_control and replace move_interface with MoveGroup (shouldn't be tooo hard, as they are similar).
- Stop using contact_control.

I'm sorry about this! We should get our act together.
